#!/usr/bin/env python3
"""Parse, validate, and render the workspace's bilateral skill graph.

The graph is maintainer metadata.  It does not participate in runtime skill
loading or authority decisions; the source body's instruction remains the
execution contract.
"""

from __future__ import annotations

import json
import re
import string
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1
RELATIONS = ("adapts", "depends_on_contract", "hands_off", "loads")
GRAPH_PATH = "concepts/relationships.json"
VIEW_NAME = "RELATIONSHIPS.md"
GENERATED_HEADER = "<!-- GENERATED by `python3 scripts/lint.py --write-relationships` — do not edit by hand. -->"

_TOP_LEVEL_KEYS = {"schema", "edges"}
_EDGE_KEYS = {"from", "to", "relation", "required", "when", "source", "reason"}
_REQUIRED_EDGE_KEYS = _EDGE_KEYS - {"when"}
_DEPLOYMENT_ALIASES = {"implement", "to-issues", "to-prd"}
_CONCEPT_NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_ATX_HEADING = re.compile(r"^ {0,3}#{1,6}[ \t]+(.+?)[ \t]*$")
_ASCII_PUNCTUATION = set(string.punctuation) - {"-", " "}


@dataclass(frozen=True)
class Edge:
    owner: str
    target: str
    relation: str
    required: bool
    when: str | None
    source: str
    reason: str


def _edge_label(index: int) -> str:
    return f"edge {index + 1}"


def _source_parts(source: str) -> tuple[str, str | None] | None:
    """Split a source reference, rejecting empty or multiply-delimited anchors."""
    if not isinstance(source, str) or not source.strip():
        return None
    if source.count("#") > 1:
        return None
    path_text, separator, fragment = source.partition("#")
    if not path_text or (separator and not fragment):
        return None
    return path_text, fragment if separator else None


def _heading_slug(heading: str) -> str:
    lowered = heading.lower()
    without_ascii_punctuation = "".join(
        character
        for character in lowered
        if character not in _ASCII_PUNCTUATION
    )
    return without_ascii_punctuation.replace(" ", "-")


def _matching_headings(text: str, fragment: str) -> list[str]:
    matches: list[str] = []
    for line in text.splitlines():
        match = _ATX_HEADING.match(line)
        if not match:
            continue
        heading = re.sub(r"[ \t]+#+[ \t]*$", "", match.group(1))
        if _heading_slug(heading) == fragment:
            matches.append(line)
    return matches


def _concept_dirs(root: Path) -> set[str]:
    concepts = root / "concepts"
    if not concepts.is_dir():
        return set()
    return {path.name for path in concepts.iterdir() if path.is_dir()}


def _is_repo_relative(path_text: str) -> bool:
    path = Path(path_text)
    return not path.is_absolute() and ".." not in path.parts and path_text not in {"", "."}


def load_graph(root: Path) -> tuple[list[Edge], list[str]]:
    """Load the forward graph, returning parsed edges and structural errors."""
    graph_path = root / GRAPH_PATH
    if not graph_path.is_file():
        return [], [f"missing graph file: {GRAPH_PATH}"]

    try:
        data = json.loads(graph_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError) as exc:
        return [], [f"could not read {GRAPH_PATH}: {exc}"]
    except json.JSONDecodeError as exc:
        return [], [f"malformed JSON in {GRAPH_PATH}: {exc.msg} at line {exc.lineno} column {exc.colno}"]

    if not isinstance(data, dict):
        return [], [f"{GRAPH_PATH} must contain a JSON object"]

    errors: list[str] = []
    unknown_top_level = sorted(set(data) - _TOP_LEVEL_KEYS)
    for key in unknown_top_level:
        errors.append(f"unknown top-level key in {GRAPH_PATH}: {key}")

    if "schema" not in data:
        errors.append(f"{GRAPH_PATH} is missing schema")
    elif type(data["schema"]) is not int or data["schema"] != SCHEMA_VERSION:
        errors.append(
            f"unsupported schema in {GRAPH_PATH}: {data['schema']!r}; expected {SCHEMA_VERSION}"
        )

    if "edges" not in data:
        errors.append(f"{GRAPH_PATH} is missing edges")
        return [], errors
    if not isinstance(data["edges"], list):
        errors.append(f"edges in {GRAPH_PATH} must be an array")
        return [], errors

    parsed: list[Edge] = []
    for index, raw_edge in enumerate(data["edges"]):
        label = _edge_label(index)
        if not isinstance(raw_edge, dict):
            errors.append(f"{label} must be an object")
            continue
        unknown_edge_keys = sorted(set(raw_edge) - _EDGE_KEYS)
        for key in unknown_edge_keys:
            errors.append(f"unknown edge key in {label}: {key}")
        missing = sorted(_REQUIRED_EDGE_KEYS - set(raw_edge))
        for key in missing:
            errors.append(f"{label} is missing {key}")
        if unknown_edge_keys or missing:
            continue
        parsed.append(
            Edge(
                owner=raw_edge["from"],
                target=raw_edge["to"],
                relation=raw_edge["relation"],
                required=raw_edge["required"],
                when=raw_edge.get("when"),
                source=raw_edge["source"],
                reason=raw_edge["reason"],
            )
        )

    if errors:
        return [], errors
    return parsed, []


def _validate_name(
    value: Any,
    field: str,
    edge_label: str,
    concept_names: set[str],
    errors: list[str],
) -> bool:
    if not isinstance(value, str) or not value:
        errors.append(f"{edge_label} {field} must be a canonical concept name")
        return False
    if value in _DEPLOYMENT_ALIASES:
        errors.append(f"{edge_label} {field} uses non-canonical deployment alias: {value}")
        return False
    if not _CONCEPT_NAME.fullmatch(value):
        errors.append(f"{edge_label} {field} is not a canonical dash-case concept name: {value}")
        return False
    if value not in concept_names:
        errors.append(f"{edge_label} {field} names unknown concept: {value}")
        return False
    return True


def _validate_source(
    root: Path,
    edge: Edge,
    index: int,
    owner_valid: bool,
    target_valid: bool,
    errors: list[str],
) -> None:
    label = _edge_label(index)
    if not isinstance(edge.source, str) or not edge.source.strip():
        errors.append(f"{label} source must be a non-empty repository-relative path")
        return
    parts = _source_parts(edge.source)
    if parts is None:
        errors.append(f"{label} source has a malformed anchor: {edge.source}")
        return
    path_text, fragment = parts
    if not _is_repo_relative(path_text):
        errors.append(f"{label} source must be repository-relative: {edge.source}")
        return

    source_path = root / path_text
    resolved_root = root.resolve()
    resolved_source = source_path.resolve()
    try:
        resolved_source.relative_to(resolved_root)
    except ValueError:
        errors.append(f"{label} source resolves outside the repository: {edge.source}")
        return

    if not resolved_source.is_file():
        errors.append(f"{label} source does not exist: {path_text}")
        return

    if owner_valid:
        owner_dir = (root / "concepts" / edge.owner).resolve()
        try:
            resolved_source.relative_to(owner_dir)
        except ValueError:
            errors.append(f"{label} source is outside its from concept: {edge.source}")
            return

    try:
        source_text = resolved_source.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"{label} source could not be read: {exc}")
        return

    if target_valid:
        mention = re.compile(rf"(?<![A-Za-z0-9-]){re.escape(edge.target)}(?![A-Za-z0-9-])")
        if mention.search(source_text) is None:
            errors.append(f"{label} source does not mention target `{edge.target}`")

    if fragment is not None:
        headings = _matching_headings(source_text, fragment)
        if not headings:
            errors.append(f"{label} source anchor #{fragment} matches no heading")
        elif len(headings) != 1:
            errors.append(
                f"{label} source anchor #{fragment} matches {len(headings)} headings"
            )


def _mandatory_load_cycles(edges: list[Edge]) -> list[str]:
    adjacency: dict[str, list[str]] = {}
    for edge in edges:
        if edge.relation == "loads" and edge.required is True:
            if isinstance(edge.owner, str) and isinstance(edge.target, str):
                adjacency.setdefault(edge.owner, []).append(edge.target)

    for owner in adjacency:
        adjacency[owner] = sorted(set(adjacency[owner]))

    state: dict[str, int] = {}
    stack: list[str] = []
    cycles: list[str] = []
    seen: set[tuple[str, ...]] = set()

    def visit(node: str) -> None:
        state[node] = 1
        stack.append(node)
        for target in adjacency.get(node, []):
            if state.get(target, 0) == 0:
                visit(target)
            elif state.get(target) == 1:
                start = stack.index(target)
                cycle = tuple(stack[start:] + [target])
                if cycle not in seen:
                    seen.add(cycle)
                    cycles.append(" -> ".join(cycle))
        stack.pop()
        state[node] = 2

    for node in sorted(adjacency):
        if state.get(node, 0) == 0:
            visit(node)
    return cycles


def validate_graph(root: Path, edges: list[Edge]) -> list[str]:
    """Return all semantic and repository-consistency violations in ``edges``."""
    errors: list[str] = []
    concept_names = _concept_dirs(root)
    identities: dict[tuple[Any, ...], int] = {}

    for index, edge in enumerate(edges):
        label = _edge_label(index)
        owner_valid = _validate_name(edge.owner, "from", label, concept_names, errors)
        target_valid = _validate_name(edge.target, "to", label, concept_names, errors)

        if isinstance(edge.owner, str) and isinstance(edge.target, str) and edge.owner == edge.target:
            errors.append(f"{label} is a self-edge: {edge.owner} -> {edge.target}")

        if not isinstance(edge.relation, str) or edge.relation not in RELATIONS:
            errors.append(f"{label} has invalid relation: {edge.relation!r}")

        if type(edge.required) is not bool:
            errors.append(f"{label} required must be boolean")

        if edge.when is not None:
            if not isinstance(edge.when, str):
                errors.append(f"{label} when must be a string or null")
            elif not edge.when.strip():
                errors.append(f"{label} when must not be blank")

        if not isinstance(edge.reason, str) or not edge.reason.strip():
            errors.append(f"{label} reason must not be empty")

        if isinstance(edge.owner, str) and isinstance(edge.target, str):
            identity = (edge.owner, edge.target, edge.relation, edge.when)
            try:
                duplicate = identity in identities
            except TypeError:
                duplicate = False
            if duplicate:
                errors.append(
                    f"{label} duplicates edge identity from edge {identities[identity] + 1}: {identity!r}"
                )
            else:
                try:
                    identities[identity] = index
                except TypeError:
                    pass

        _validate_source(root, edge, index, owner_valid, target_valid, errors)

    for cycle in _mandatory_load_cycles(edges):
        errors.append(f"mandatory loads cycle: {cycle}")

    return errors
