#!/usr/bin/env python3
"""Parse, validate, and render the workspace's bilateral skill graph.

The graph is maintainer metadata.  It does not participate in runtime skill
loading or authority decisions; the source body's instruction remains the
execution contract.
"""

from __future__ import annotations

import json
import re
import string
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1
RELATIONS = ("adapts", "depends_on_contract", "hands_off", "loads")
GRAPH_PATH = "concepts/relationships.json"
VIEW_NAME = "RELATIONSHIPS.md"
GENERATED_HEADER = "<!-- GENERATED by `python3 scripts/lint.py --write-relationships` — do not edit by hand. -->"

_TOP_LEVEL_KEYS = {"schema", "edges"}
_EDGE_KEYS = {"from", "to", "relation", "required", "when", "source", "reason"}
_REQUIRED_EDGE_KEYS = _EDGE_KEYS - {"when"}
_DEPLOYMENT_ALIASES = {"implement", "to-issues", "to-prd"}
_CONCEPT_NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_ATX_HEADING = re.compile(r"^ {0,3}#{1,6}[ \t]+(.+?)[ \t]*$")
_ASCII_PUNCTUATION = set(string.punctuation) - {"-", " "}


@dataclass(frozen=True)
class Edge:
    owner: str
    target: str
    relation: str
    required: bool
    when: str | None
    source: str
    reason: str


def _edge_label(index: int) -> str:
    return f"edge {index + 1}"


def _source_parts(source: str) -> tuple[str, str | None] | None:
    """Split a source reference, rejecting empty or multiply-delimited anchors."""
    if not isinstance(source, str) or not source.strip():
        return None
    if source.count("#") > 1:
        return None
    path_text, separator, fragment = source.partition("#")
    if not path_text or (separator and not fragment):
        return None
    return path_text, fragment if separator else None


def _heading_slug(heading: str) -> str:
    lowered = heading.lower()
    without_ascii_punctuation = "".join(
        character
        for character in lowered
        if character not in _ASCII_PUNCTUATION
    )
    return without_ascii_punctuation.replace(" ", "-")


def _matching_headings(text: str, fragment: str) -> list[str]:
    matches: list[str] = []
    for line in text.splitlines():
        match = _ATX_HEADING.match(line)
        if not match:
            continue
        heading = re.sub(r"[ \t]+#+[ \t]*$", "", match.group(1))
        if _heading_slug(heading) == fragment:
            matches.append(line)
    return matches


def _concept_dirs(root: Path) -> set[str]:
    concepts = root / "concepts"
    if not concepts.is_dir():
        return set()
    return {path.name for path in concepts.iterdir() if path.is_dir()}


def _is_repo_relative(path_text: str) -> bool:
    path = Path(path_text)
    return not path.is_absolute() and ".." not in path.parts and path_text not in {"", "."}


def load_graph(root: Path) -> tuple[list[Edge], list[str]]:
    """Load the forward graph, returning parsed edges and structural errors."""
    graph_path = root / GRAPH_PATH
    if not graph_path.is_file():
        return [], [f"missing graph file: {GRAPH_PATH}"]

    try:
        data = json.loads(graph_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError) as exc:
        return [], [f"could not read {GRAPH_PATH}: {exc}"]
    except json.JSONDecodeError as exc:
        return [], [f"malformed JSON in {GRAPH_PATH}: {exc.msg} at line {exc.lineno} column {exc.colno}"]

    if not isinstance(data, dict):
        return [], [f"{GRAPH_PATH} must contain a JSON object"]

    errors: list[str] = []
    unknown_top_level = sorted(set(data) - _TOP_LEVEL_KEYS)
    for key in unknown_top_level:
        errors.append(f"unknown top-level key in {GRAPH_PATH}: {key}")

    if "schema" not in data:
        errors.append(f"{GRAPH_PATH} is missing schema")
    elif type(data["schema"]) is not int or data["schema"] != SCHEMA_VERSION:
        errors.append(
            f"unsupported schema in {GRAPH_PATH}: {data['schema']!r}; expected {SCHEMA_VERSION}"
        )

    if "edges" not in data:
        errors.append(f"{GRAPH_PATH} is missing edges")
        return [], errors
    if not isinstance(data["edges"], list):
        errors.append(f"edges in {GRAPH_PATH} must be an array")
        return [], errors

    parsed: list[Edge] = []
    for index, raw_edge in enumerate(data["edges"]):
        label = _edge_label(index)
        if not isinstance(raw_edge, dict):
            errors.append(f"{label} must be an object")
            continue
        unknown_edge_keys = sorted(set(raw_edge) - _EDGE_KEYS)
        for key in unknown_edge_keys:
            errors.append(f"unknown edge key in {label}: {key}")
        missing = sorted(_REQUIRED_EDGE_KEYS - set(raw_edge))
        for key in missing:
            errors.append(f"{label} is missing {key}")
        if unknown_edge_keys or missing:
            continue
        parsed.append(
            Edge(
                owner=raw_edge["from"],
                target=raw_edge["to"],
                relation=raw_edge["relation"],
                required=raw_edge["required"],
                when=raw_edge.get("when"),
                source=raw_edge["source"],
                reason=raw_edge["reason"],
            )
        )

    if errors:
        return [], errors
    return parsed, []


def _validate_name(
    value: Any,
    field: str,
    edge_label: str,
    concept_names: set[str],
    errors: list[str],
) -> bool:
    if not isinstance(value, str) or not value:
        errors.append(f"{edge_label} {field} must be a canonical concept name")
        return False
    if value in _DEPLOYMENT_ALIASES:
        errors.append(f"{edge_label} {field} uses non-canonical deployment alias: {value}")
        return False
    if not _CONCEPT_NAME.fullmatch(value):
        errors.append(f"{edge_label} {field} is not a canonical dash-case concept name: {value}")
        return False
    if value not in concept_names:
        errors.append(f"{edge_label} {field} names unknown concept: {value}")
        return False
    return True


def _validate_source(
    root: Path,
    edge: Edge,
    index: int,
    owner_valid: bool,
    target_valid: bool,
    errors: list[str],
) -> None:
    label = _edge_label(index)
    if not isinstance(edge.source, str) or not edge.source.strip():
        errors.append(f"{label} source must be a non-empty repository-relative path")
        return
    parts = _source_parts(edge.source)
    if parts is None:
        errors.append(f"{label} source has a malformed anchor: {edge.source}")
        return
    path_text, fragment = parts
    if not _is_repo_relative(path_text):
        errors.append(f"{label} source must be repository-relative: {edge.source}")
        return

    source_path = root / path_text
    resolved_root = root.resolve()
    resolved_source = source_path.resolve()
    try:
        resolved_source.relative_to(resolved_root)
    except ValueError:
        errors.append(f"{label} source resolves outside the repository: {edge.source}")
        return

    if not resolved_source.is_file():
        errors.append(f"{label} source does not exist: {path_text}")
        return

    if owner_valid:
        owner_dir = (root / "concepts" / edge.owner).resolve()
        try:
            resolved_source.relative_to(owner_dir)
        except ValueError:
            errors.append(f"{label} source is outside its from concept: {edge.source}")
            return

    try:
        source_text = resolved_source.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"{label} source could not be read: {exc}")
        return

    if target_valid:
        mention = re.compile(rf"(?<![A-Za-z0-9-]){re.escape(edge.target)}(?![A-Za-z0-9-])")
        if mention.search(source_text) is None:
            errors.append(f"{label} source does not mention target `{edge.target}`")

    if fragment is not None:
        headings = _matching_headings(source_text, fragment)
        if not headings:
            errors.append(f"{label} source anchor #{fragment} matches no heading")
        elif len(headings) != 1:
            errors.append(
                f"{label} source anchor #{fragment} matches {len(headings)} headings"
            )


def _mandatory_load_cycles(edges: list[Edge]) -> list[str]:
    adjacency: dict[str, list[str]] = {}
    for edge in edges:
        if edge.relation == "loads" and edge.required is True:
            if isinstance(edge.owner, str) and isinstance(edge.target, str):
                adjacency.setdefault(edge.owner, []).append(edge.target)

    for owner in adjacency:
        adjacency[owner] = sorted(set(adjacency[owner]))

    state: dict[str, int] = {}
    stack: list[str] = []
    cycles: list[str] = []
    seen: set[tuple[str, ...]] = set()

    def visit(node: str) -> None:
        state[node] = 1
        stack.append(node)
        for target in adjacency.get(node, []):
            if state.get(target, 0) == 0:
                visit(target)
            elif state.get(target) == 1:
                start = stack.index(target)
                cycle = tuple(stack[start:] + [target])
                if cycle not in seen:
                    seen.add(cycle)
                    cycles.append(" -> ".join(cycle))
        stack.pop()
        state[node] = 2

    for node in sorted(adjacency):
        if state.get(node, 0) == 0:
            visit(node)
    return cycles


def validate_graph(root: Path, edges: list[Edge]) -> list[str]:
    """Return all semantic and repository-consistency violations in ``edges``."""
    errors: list[str] = []
    concept_names = _concept_dirs(root)
    identities: dict[tuple[Any, ...], int] = {}

    for index, edge in enumerate(edges):
        label = _edge_label(index)
        owner_valid = _validate_name(edge.owner, "from", label, concept_names, errors)
        target_valid = _validate_name(edge.target, "to", label, concept_names, errors)

        if isinstance(edge.owner, str) and isinstance(edge.target, str) and edge.owner == edge.target:
            errors.append(f"{label} is a self-edge: {edge.owner} -> {edge.target}")

        if not isinstance(edge.relation, str) or edge.relation not in RELATIONS:
            errors.append(f"{label} has invalid relation: {edge.relation!r}")

        if type(edge.required) is not bool:
            errors.append(f"{label} required must be boolean")

        if edge.when is not None:
            if not isinstance(edge.when, str):
                errors.append(f"{label} when must be a string or null")
            elif not edge.when.strip():
                errors.append(f"{label} when must not be blank")

        if not isinstance(edge.reason, str) or not edge.reason.strip():
            errors.append(f"{label} reason must not be empty")

        if isinstance(edge.owner, str) and isinstance(edge.target, str):
            identity = (edge.owner, edge.target, edge.relation, edge.when)
            try:
                duplicate = identity in identities
            except TypeError:
                duplicate = False
            if duplicate:
                errors.append(
                    f"{label} duplicates edge identity from edge {identities[identity] + 1}: {identity!r}"
                )
            else:
                try:
                    identities[identity] = index
                except TypeError:
                    pass

        _validate_source(root, edge, index, owner_valid, target_valid, errors)

    for cycle in _mandatory_load_cycles(edges):
        errors.append(f"mandatory loads cycle: {cycle}")

    return errors


def _condition_suffix(edge: Edge) -> str:
    requiredness = "required" if edge.required else "optional"
    if edge.when is None:
        return f"{requiredness}."
    return f"{requiredness}, when {edge.when}."


def _outgoing_verb(edge: Edge) -> str:
    if edge.relation == "loads":
        return f"loads `{edge.target}`"
    if edge.relation == "adapts":
        return f"adapts `{edge.target}`"
    if edge.relation == "depends_on_contract":
        return f"depends on `{edge.target}`'s contract"
    if edge.relation == "hands_off":
        return f"hands off to `{edge.target}`"
    raise ValueError(f"unknown relationship: {edge.relation}")


def _incoming_verb(edge: Edge) -> str:
    if edge.relation == "loads":
        return "loads this concept"
    if edge.relation == "adapts":
        return "adapts this concept"
    if edge.relation == "depends_on_contract":
        return "depends on this concept's contract"
    if edge.relation == "hands_off":
        return "hands off to this concept"
    raise ValueError(f"unknown relationship: {edge.relation}")


def _source_link(edge: Edge, name: str, incoming: bool) -> tuple[str, str]:
    source_parts = _source_parts(edge.source)
    if source_parts is None:
        # Rendering is normally reached only after validation. Keeping this
        # fallback deterministic makes malformed fixture edges inspectable.
        path_text, fragment = edge.source, None
    else:
        path_text, fragment = source_parts

    # Use POSIX path arithmetic so generated Markdown is stable across
    # platforms; source references in the graph are repository-relative.
    import posixpath

    href_text = posixpath.relpath(path_text, posixpath.join("concepts", name))
    label = path_text.removeprefix("concepts/") if incoming else href_text

    if fragment is not None:
        href_text += f"#{fragment}"
    return label, href_text


def _outgoing_row(edge: Edge, name: str) -> list[str]:
    label, href = _source_link(edge, name, incoming=False)
    return [
        f"- {_outgoing_verb(edge)} — {_condition_suffix(edge)}",
        f"  {edge.reason}",
        f"  Source: [{label}]({href})",
    ]


def _incoming_row(edge: Edge, name: str) -> list[str]:
    label, href = _source_link(edge, name, incoming=True)
    return [
        f"- incoming from [{edge.owner}](../{edge.owner}/{VIEW_NAME}): "
        f"{_incoming_verb(edge)} — {_condition_suffix(edge)}",
        f"  {edge.reason}",
        f"  Source: [{label}]({href})",
    ]


def render_view(name: str, edges: list[Edge]) -> str:
    """Render one concept's direct outgoing and incoming relationship view."""
    outgoing = sorted(
        (edge for edge in edges if edge.owner == name),
        key=lambda edge: (edge.target, edge.relation, edge.when or ""),
    )
    incoming = sorted(
        (edge for edge in edges if edge.target == name),
        key=lambda edge: (edge.owner, edge.relation, edge.when or ""),
    )

    outgoing_lines: list[str] = []
    for edge in outgoing:
        if outgoing_lines:
            outgoing_lines.append("")
        outgoing_lines.extend(_outgoing_row(edge, name))
    if not outgoing_lines:
        outgoing_lines = ["None."]

    incoming_lines: list[str] = []
    for edge in incoming:
        if incoming_lines:
            incoming_lines.append("")
        incoming_lines.extend(_incoming_row(edge, name))
    if not incoming_lines:
        incoming_lines = ["None."]

    lines = [
        GENERATED_HEADER,
        "",
        f"# {name} relationships",
        "",
        "Source of truth is [concepts/relationships.json](../relationships.json). Regenerate with",
        "`python3 scripts/lint.py --write-relationships`; `python3 scripts/lint.py` fails while this file is stale.",
        "",
        "## Outgoing",
        "",
        *outgoing_lines,
        "",
        "## Incoming",
        "",
        *incoming_lines,
        "",
    ]
    return "\n".join(lines)


def render_all(edges: list[Edge]) -> dict[str, str]:
    """Render direct views for concepts participating in at least one edge."""
    names = sorted({edge.owner for edge in edges} | {edge.target for edge in edges})
    return {name: render_view(name, edges) for name in names}


def _view_path(root: Path, name: str) -> Path:
    return root / "concepts" / name / VIEW_NAME


def _existing_view_names(root: Path) -> set[str]:
    concepts = root / "concepts"
    if not concepts.is_dir():
        return set()
    names: set[str] = set()
    for concept in concepts.iterdir():
        if concept.is_dir() and (concept / VIEW_NAME).exists():
            names.add(concept.name)
    return names


def check_views(root: Path, edges: list[Edge]) -> list[str]:
    """Return missing, extra, and stale generated-view errors without mutating."""
    expected = render_all(edges)
    errors: list[str] = []

    for name in sorted(expected):
        view = _view_path(root, name)
        relative = view.relative_to(root)
        if not view.is_file():
            errors.append(f"missing generated relationship view: {relative}")
        else:
            try:
                actual = view.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError) as exc:
                errors.append(f"could not read generated relationship view {relative}: {exc}")
            else:
                if actual != expected[name]:
                    errors.append(f"stale generated relationship view: {relative}")

    expected_names = set(expected)
    for name in sorted(_existing_view_names(root) - expected_names):
        errors.append(f"extra generated relationship view: {_view_path(root, name).relative_to(root)}")

    return errors


def write_views(root: Path, edges: list[Edge]) -> list[str]:
    """Write changed generated views and remove views for concepts without edges."""
    expected = render_all(edges)
    changed: list[str] = []

    for name in sorted(expected):
        view = _view_path(root, name)
        content = expected[name]
        if view.is_file() and view.read_text(encoding="utf-8") == content:
            continue
        view.parent.mkdir(parents=True, exist_ok=True)
        view.write_text(content, encoding="utf-8")
        changed.append(str(view.relative_to(root)))

    expected_names = set(expected)
    concepts = root / "concepts"
    if concepts.is_dir():
        for concept in sorted((path for path in concepts.iterdir() if path.is_dir()), key=lambda path: path.name):
            if concept.name in expected_names:
                continue
            view = concept / VIEW_NAME
            if not view.is_file() and not view.is_symlink():
                continue
            view.unlink()
            changed.append(str(view.relative_to(root)))

    return sorted(changed)
